### ISSUE TITLE
Validation errors could be more meaningful

### ISSUE THREAD

**Issue by enricoschuetz** [web-of-things-open-source/tm-catalog-cli#1]
The logged validation errors could be more meaningful to help the user to fix the invalid Thing Model Json files.

1.  The validation errors should contain the currently processed file name.
     
     Reason: 
     If you call the CLI tool e.g. in a script that makes a batch "push", then you do not know to which
     files the logged errors belong to. 
     
2. When the required metadata are validated (like `"schema:manufacturer"`), then the logged error messages
   refer to the properties of the internal used model, not to the actual required Json property names.
   
   Current example:
   `msg="validation failed" error="Key: 'ThingModel.Manufacturer' Error:Field validation for 'Manufacturer' failed on the 'required' tag\nKey`     
   
   But the user would rather know that `"schema:manufacturer"` is missing.

3. When the `@type` is missing in the TM file, the validation error does not point at the problem: `validation error: not all required properties were found`

**Comment by alexbrdn** [comment]
I believe point 1 is fixed by #13

**Comment by alexbrdn** [comment]
EDIT: added point 3 to description

**Comment by alexbrdn** [comment]
I believe points 2 and 3 are fixed by https://github.com/web-of-things-open-source/tm-catalog-cli/pull/19
@enricoschuetz, please confirm

**Comment by alexbrdn** [comment]
Yes, I believe it reports the id of the schema, or maybe expands it if it's not absolute. Not sure

**Comment by alexbrdn** [comment]
I've adjusted the urls for embedded resources in code so that the error message now reads e.g. like this:
> validation error: jsonschema: '' does not validate with resource://tmc-mandatory.schema.json#/required: missing properties: 'schema:manufacturer'

I think that's the best we can do for now. Because any partial URL without a schema gets expanded by the validation library within the context of the current workdir.
